### ISSUE TITLE
[Siga-Doc] Busca de documentos pela caixa de pesquisa não está funcionando

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#102]
Ao digitar o número de um documento na caixa de pesquisa localizada no canto superior direito o sistema não está localizando o respectivo documento.

Como reproduzir:
1. Digite JFRJ-POR-2015/00001 na caixa de pesquisa e pressione TAB
2. O sistema deveria completar o texto digitado com "-A" e redirecionar a página para o documento

Ilustração:

![image](https://cloud.githubusercontent.com/assets/2985140/5838358/12d79436-a16e-11e4-9828-d318727ff3bf.png)

**Comment by kmacedovarela** [comment]
@hodrigohamalho já viu esse né.

20:32:38,614 INFO  [br.gov.jfrj.siga.base.SigaHTTP] (http-/10.10.0.69:8380-52) Nao encontrou o set-cookie
20:32:38,615 INFO  [br.gov.jfrj.siga.base.SigaHTTP] (http-/10.10.0.69:8380-52) retornando string vazia
20:32:38,616 ERROR [stderr] (http-/10.10.0.69:8380-52) java.lang.NullPointerException
20:32:38,617 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.siga.base.SigaHTTP.getIdp(SigaHTTP.java:174)
20:32:38,617 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.siga.base.SigaHTTP.get(SigaHTTP.java:101)
20:32:38,618 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.webwork.action.PrincipalAction.aSelecionar(PrincipalAction.java:167)
20:32:38,618 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:32:38,618 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
20:32:38,618 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:32:38,619 ERROR [stderr] (http-/10.10.0.69:8380-52)  at java.lang.reflect.Method.invoke(Method.java:606)
20:32:38,619 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:358)
20:32:38,619 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:218)
20:32:38,619 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:192)
20:32:38,620 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,620 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,620 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,620 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,621 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,621 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,621 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,622 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,622 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,622 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,622 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:186)
20:32:38,623 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,623 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.webwork.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:174)
20:32:38,623 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,623 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionProxy.execute(DefaultActionProxy.java:116)
20:32:38,624 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.webwork.dispatcher.DispatcherUtils.serviceAction(DispatcherUtils.java:273)
20:32:38,624 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.webwork.dispatcher.FilterDispatcher.doFilter(FilterDispatcher.java:202)
20:32:38,624 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
20:32:38,625 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
20:32:38,625 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.siga.util.HibernateThreadFilter.doFiltro(HibernateThreadFilter.java:135)
20:32:38,625 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.siga.util.HibernateThreadFilter.executaFiltro(HibernateThreadFilter.java:126)
20:32:38,626 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.siga.util.HibernateThreadFilter.doFilter(HibernateThreadFilter.java:61)
20:32:38,626 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
20:32:38,626 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
20:32:38,626 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
20:32:38,627 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
20:32:38,627 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
20:32:38,627 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
20:32:38,628 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499)
20:32:38,628 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
20:32:38,628 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
20:32:38,628 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
20:32:38,629 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
20:32:38,629 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
20:32:38,629 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
20:32:38,630 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
20:32:38,630 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920)
20:32:38,630 ERROR [stderr] (http-/10.10.0.69:8380-52)  at java.lang.Thread.run(Thread.java:745)
20:32:38,638 ERROR [stderr] (http-/10.10.0.69:8380-52) javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
20:32:38,638 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
20:32:38,638 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884)
20:32:38,639 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
20:32:38,639 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
20:32:38,639 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1439)
20:32:38,640 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209)
20:32:38,640 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.Handshaker.processLoop(Handshaker.java:878)
20:32:38,640 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.Handshaker.process_record(Handshaker.java:814)
20:32:38,640 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016)
20:32:38,641 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
20:32:38,641 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
20:32:38,641 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
20:32:38,641 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
20:32:38,642 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
20:32:38,642 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
20:32:38,642 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
20:32:38,643 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
20:32:38,643 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
20:32:38,643 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
20:32:38,643 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
20:32:38,644 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
20:32:38,644 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
20:32:38,644 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
20:32:38,644 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
20:32:38,645 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
20:32:38,645 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.http.client.fluent.Request.execute(Request.java:143)
20:32:38,645 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.siga.base.SigaHTTP.get(SigaHTTP.java:101)
20:32:38,646 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.webwork.action.PrincipalAction.aSelecionar(PrincipalAction.java:167)
20:32:38,646 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:32:38,646 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
20:32:38,646 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:32:38,647 ERROR [stderr] (http-/10.10.0.69:8380-52)  at java.lang.reflect.Method.invoke(Method.java:606)
20:32:38,647 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:358)
20:32:38,647 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:218)
20:32:38,648 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:192)
20:32:38,648 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,648 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,648 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,649 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,649 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,649 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,649 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,650 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,650 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:31)
20:32:38,650 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,650 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:186)
20:32:38,651 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,651 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.webwork.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:174)
20:32:38,651 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:190)
20:32:38,652 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.xwork.DefaultActionProxy.execute(DefaultActionProxy.java:116)
20:32:38,652 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.webwork.dispatcher.DispatcherUtils.serviceAction(DispatcherUtils.java:273)
20:32:38,652 ERROR [stderr] (http-/10.10.0.69:8380-52)  at com.opensymphony.webwork.dispatcher.FilterDispatcher.doFilter(FilterDispatcher.java:202)
20:32:38,652 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
20:32:38,653 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
20:32:38,653 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.siga.util.HibernateThreadFilter.doFiltro(HibernateThreadFilter.java:135)
20:32:38,653 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.siga.util.HibernateThreadFilter.executaFiltro(HibernateThreadFilter.java:126)
20:32:38,653 ERROR [stderr] (http-/10.10.0.69:8380-52)  at br.gov.jfrj.siga.util.HibernateThreadFilter.doFilter(HibernateThreadFilter.java:61)
20:32:38,654 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
20:32:38,654 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
20:32:38,654 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
20:32:38,654 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
20:32:38,655 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
20:32:38,655 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
20:32:38,655 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:499)
20:32:38,656 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
20:32:38,656 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
20:32:38,656 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
20:32:38,656 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
20:32:38,657 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
20:32:38,657 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
20:32:38,657 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
20:32:38,658 ERROR [stderr] (http-/10.10.0.69:8380-52)  at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920)
20:32:38,658 ERROR [stderr] (http-/10.10.0.69:8380-52)  at java.lang.Thread.run(Thread.java:745)
20:32:38,658 ERROR [stderr] (http-/10.10.0.69:8380-52) Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
20:32:38,659 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
20:32:38,659 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
20:32:38,659 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.validator.Validator.validate(Validator.java:260)
20:32:38,659 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
20:32:38,660 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
20:32:38,660 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
20:32:38,660 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1421)
20:32:38,660 ERROR [stderr] (http-/10.10.0.69:8380-52)  ... 68 more
20:32:38,661 ERROR [stderr] (http-/10.10.0.69:8380-52) Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
20:32:38,661 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
20:32:38,661 ERROR [stderr] (http-/10.10.0.69:8380-52)  at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
20:32:38,662 ERROR [stderr] (http-/10.10.0.69:8380-52)  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
20:32:38,662 ERROR [stderr] (http-/10.10.0.69:8380-52)  ... 74 more

**Comment by hodrigohamalho** [comment]
Corrigido, caso volte a acontecer, favor reabrir.

**Comment by Markenson** [comment]
Este problema voltou a ocorrer em produção.

**Comment by kmacedovarela** [comment]
Procede, estou verificando.

**Comment by kmacedovarela** [comment]
É possível reproduzir o erro em homologação da seguinte maneira e com o seguinte documento JFRJ-SEC-2015/00007:
 
Acessar a aplicação
Tentar consultar (Vai funcionar)
Apagar os cookies
Tentar consultar  (Não vai funcionar)

**Comment by kmacedovarela** [comment]
Causa do erro identificada:

@hodrigohamalho Na SigaHTTP:209 método getIdp, quando o cookie é apagado, ele não se adequa a nenhum caso implementado, e o IDP retornado é nulo.

**Comment by hodrigohamalho** [comment]
Corrigido.
